### ISSUE TITLE
Issue with batteryLevel

### ISSUE THREAD

**Issue by cbijon** [LukePrior/TTN-BME280-Weather-Station-Heltec-CubeCell-HTCC-AB01#1]
Hello,

I have tested your code, and i think you have an issue. After some hours running, batteryLevel return 0% but it's not true.

Do you have the same ?

Best regards,

Charles

**Comment by LukePrior** [comment]
Hi Charles,

The batteryLevel variable returns 0 or 100 based on the battery voltage, if the voltage is less than 4.2V the value is 0.

I personally use batteryVoltage to monitor the battery level of my setup.

You can edit line 55 in main.ino to change the calculation of batteryLevel

Thanks
